### ISSUE TITLE
2023-09-21 PROJECT TODO

### ISSUE THREAD

**Issue by honghyunshik** [honghyunshik/study-record#19]
- [x] Invalid Jwt 401 반환하기
- [ ] 소셜로그인 시 DB에 사용자정보 저장
- [x] Refresh Token Logic 수정
- [x] NoSQL TTL 확인
